Admin dashboard
e-campus-org/ecampus pull request #3
Opened 2024-09-30 19:22 UTC by DryunjaS

2024-10-03 19:17 UTC, shekshuev reviewed
Есть много дублированного функционала, но его можно потом отрефакторить. Остальные замечания выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/components/widgets/accounts/list-widget.vue
> -</script> -->
не оставляй закоментированный код. Не нужен, удаляй. Нужно будет вернуться к нему - посмотришь историю гита

2024-10-03 19:17 UTC, shekshuev commented on frontend/components/widgets/lessons/edit-modal.vue
> +        titleErrorMessages.value.push(props.err.title || "Title is required.");
Тут и ниже ошибки в переводы перенести

2024-10-03 19:17 UTC, shekshuev commented on frontend/components/widgets/lessons/list-widget.vue
> +    data: Shared.ListData<Lessons.ReadSpecialityDTO> | null;
Почему ReadSpecialityDTO?

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/lessons/index.vue
> +            console.error("Ошибка при получении данных:", error);
Надо юзеру сообщить об ошибке. Показать нотификацию. Посмотри useEvent. Ну и текст в файлы с переводами

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/lessons/index.vue
> +            console.error("Ошибка при отправке данных на сервер:", error);
аналогично, что и выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/lessons/index.vue
> +        console.error("Ошибка при отправке данных на сервер:", error);
Аналогично см. выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/lessons/index.vue
> +        console.error("Ошибка при удалении элемента:", error);
Аналогично см. выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/subjects.vue
> +            console.error("Ошибка при получении данных:", error);
Аналогично см. выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/subjects.vue
> +            console.error("Ошибка при отправке данных на сервер:", error);
Аналогично см. выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/subjects.vue
> +        console.error("Ошибка при отправке данных на сервер:", error);
Аналогично см. выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/subjects.vue
> +        console.error("Ошибка при удалении элемента:", error);
Аналогично см. выше

2024-10-03 19:17 UTC, shekshuev commented on frontend/components/widgets/specialities/edit-modal.vue
> +        titleErrorMessages.value.push(props.err.title || "Title is required.");
в файл с переводами

2024-10-03 19:17 UTC, shekshuev commented on frontend/components/widgets/subjects/delete-modul.vue
> +    window.removeEventListener("keydown", handleKeydown);
повторяется функционал с перехватыванием enter. Напрашивается хук

2024-10-03 19:17 UTC, shekshuev commented on frontend/pages/admin/groups.vue
> +            console.error("Ошибка при отправке данных на сервер:", error);
надо юзеру показать ошибку, ниже аналогичные catch блоки есть. Посмотри на useEvent

2024-10-11 16:14 UTC, DryunjaS commented on frontend/components/widgets/accounts/edit-modal.vue
>          lastNameErrorMessages.value.push(props.err.lastName || "Last name is required.");
Значение props.err.lastName берется из переводов. Вот значение props.err 
const editModalErrors = computed(() => ({
    email: t("components.widgets.accounts.error.email"),
    firstName: t("components.widgets.accounts.error.firstName"),
    group: t("components.widgets.accounts.error.group"),
    lastName: t("components.widgets.accounts.error.lastName"),
    rolesRequired: t("components.widgets.accounts.error.rolesRequired"),
    rolesSame: t("components.widgets.accounts.error.rolesSame"),
    password: t("components.widgets.accounts.error.password"),
    passwordConfirmation: t("components.widgets.accounts.error.passwordConfirmation")
}));

2024-10-11 16:15 UTC, DryunjaS commented on frontend/components/widgets/accounts/edit-modal.vue
> +        rolesErrorMessages.value.push(props.err.rolesRequired || "Roles are required.");
Аналогично, props.err есть в переводах

2024-10-11 16:15 UTC, DryunjaS commented on frontend/components/widgets/accounts/edit-modal.vue
> +                "You cannot have the roles 'admin' and 'student' or 'teacher' and 'student' at the same time"
Поправил

2024-10-11 16:38 UTC, DryunjaS commented on frontend/pages/admin/subjects.vue
> +        console.error("Ошибка при удалении элемента:", error);
Поправил:   console.error(t("components.pages.errors.deleteData"), error);

2024-10-11 16:49 UTC, DryunjaS commented on frontend/pages/admin/groups.vue
> +            console.error("Ошибка при отправке данных на сервер:", error);
Поправил             useEvent("notify:error", t("components.pages.errors.saveData"));

2024-10-11 17:16 UTC, DryunjaS commented on frontend/components/widgets/subjects/delete-modul.vue
> +    window.removeEventListener("keydown", handleKeydown);
Сделал хук 
useKeydownListener((event: KeyboardEvent) => {
    if (event.key === "Enter") {
        remove();
    }
});

2024-10-11 17:18 UTC, DryunjaS commented on frontend/assets/locales/ru.json
> +                    "rolesSame": "У вас не могут быть роли 'администратор' и 'ученик' или 'учитель' и 'ученица' одновременно.",
Поправил                     
"rolesSame": "У вас не могут быть роли 'администратор' и 'ученик' или 'учитель' и 'ученик' одновременно.",

2024-10-11 17:18 UTC, DryunjaS commented
Исправил замечания

2024-10-14 18:12 UTC, shekshuev commented on frontend/pages/admin/lessons/index.vue
> +            console.error("Ошибка при получении данных:", error);
console.error - это все еще запись в консоль. У тебя не загрузились данные, то есть крутилка на странице пропала и все, пусто. Как пользователь узнает, что произошло? Тут нужна нотификация

2024-10-14 18:20 UTC, shekshuev requested changes
Доисправь, пожалуйста, недостатки. Остались мелочи

2024-10-14 18:20 UTC, shekshuev commented on frontend/nuxt.config.ts
> +            apiUrl: process.env.URL_VUE_APP
Верни значение apiUrl: "" и используй NUXT_PUBLIC_API_URL переменную

2024-10-14 18:20 UTC, shekshuev commented on frontend/pages/admin/specialities.vue
> +            useEvent("notify:error", t("components.pages.errors.saveData"));
Вот тут правильно сделал. А в некоторых местах пропустил

2024-10-14 18:20 UTC, shekshuev commented on frontend/pages/admin/subjects.vue
> +            console.error(t("components.pages.errors.getData"), error);
useNotify

2024-10-25 17:50 UTC, shekshuev approved these changes

2024-10-25 19:47 UTC, merged